function Hd = test
%TEST Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 18-Dec-2018 00:02:21

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 50;  % Sampling Frequency

Fpass = 20;              % Passband Frequency
Fstop = 20.1;            % Stopband Frequency
Dpass = 0.028774368332;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
