function Hd = test3
%TEST3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 18-Dec-2018 00:57:05

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 50;  % Sampling Frequency

Fstop1 = 10;              % First Stopband Frequency
Fpass1 = 11;              % First Passband Frequency
Fpass2 = 15;              % Second Passband Frequency
Fstop2 = 16;              % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
